In [1]:
print(10**(1/2))

3.1622776601683795


In [33]:
import numpy as np


In [3]:
a=np.zeros(10)

In [4]:
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
a.dtype

dtype('float64')

In [9]:
np.zeros((2,3),int)

array([[0, 0, 0],
       [0, 0, 0]])

In [10]:
a= np.zeros((2,3,2),int)

In [11]:
a[0][1][1]

0

In [12]:
a[1:3]

array([[[0, 0],
        [0, 0],
        [0, 0]]])

In [13]:
a[:2]

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]]])

In [14]:
print(a)

[[[0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]]]


In [15]:
print(a.shape)

(2, 3, 2)


In [16]:
a=np.array([1,2,3])
b=np.array([1,2,3])
print(a+b)

[2 4 6]


In [17]:
print(a*2)

[2 4 6]


In [18]:
print(a**2)

[1 4 9]


In [19]:
print(a*b)

[1 4 9]


In [20]:
print(a**b)

[ 1  4 27]


In [21]:
a.sum()

6

In [22]:
a.mean()

2.0

In [23]:
b=([5,6,7])

In [24]:
print((((a-b)**2)).sum())

48


In [25]:
a1=np.array([[1,2],[3,4]])
a2=np.array([[10,20],[30,40]])
a1.dot(a2)#dot product of 2d matrix

array([[ 70, 100],
       [150, 220]])

In [1]:
import pandas as pd

In [2]:
iris=pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data",header=None)

In [3]:
print(type(iris))

<class 'pandas.core.frame.DataFrame'>


In [4]:
df=iris.copy

In [5]:
df

<bound method NDFrame.copy of        0    1    2    3               4
0    5.1  3.5  1.4  0.2     Iris-setosa
1    4.9  3.0  1.4  0.2     Iris-setosa
2    4.7  3.2  1.3  0.2     Iris-setosa
3    4.6  3.1  1.5  0.2     Iris-setosa
4    5.0  3.6  1.4  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

[150 rows x 5 columns]>

In [6]:
df.columns=['sl','sf','pl','pw','flowertype']
df.head()

AttributeError: 'method' object has no attribute 'columns'

In [33]:
df.describe

AttributeError: 'function' object has no attribute 'describe'

In [37]:
df=pd.isnull()

TypeError: isna() missing 1 required positional argument: 'obj'

In [43]:
df=iris.copy()
df.isnull().sum()

0    0
1    0
2    0
3    0
4    0
dtype: int64

In [45]:
df=iris.copy()
df.iloc(1.3,2.4)

TypeError: __call__() takes from 1 to 2 positional arguments but 3 were given

In [40]:
df.drop(0)

AttributeError: 'function' object has no attribute 'drop'

In [41]:
a=df.drop(0)
a.head()

AttributeError: 'function' object has no attribute 'drop'

In [46]:
df=iris.copy()
df.drop(0,inplace=True)

In [47]:
# data frame consists of rows and columns

In [7]:
iris=pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data")

In [8]:
df=iris.copy()

In [9]:
df

5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]

In [10]:
df.head()

5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa

In [53]:
df.tail(7)

5.1  3.5  1.4  0.2     Iris-setosa
142  6.8  3.2  5.9  2.3  Iris-virginica
143  6.7  3.3  5.7  2.5  Iris-virginica
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

In [54]:
print(df.shape)

(149, 5)


In [55]:
print(df.dtypes)

5.1            float64
3.5            float64
1.4            float64
0.2            float64
Iris-setosa     object
dtype: object


In [56]:
df.describe()

5.1         3.5         1.4         0.2
count  149.000000  149.000000  149.000000  149.000000
mean     5.848322    3.051007    3.774497    1.205369
std      0.828594    0.433499    1.759651    0.761292
min      4.300000    2.000000    1.000000    0.100000
25%      5.100000    2.800000    1.600000    0.300000
50%      5.800000    3.000000    4.400000    1.300000
75%      6.400000    3.300000    5.100000    1.800000
max      7.900000    4.400000    6.900000    2.500000

In [11]:
df.drop(0)

5.1  3.5  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
5    4.6  3.4  1.4  0.3     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[148 rows x 5 columns]

In [12]:
df.columns=['sl','sw','pl','pw','flowertype']

In [13]:
df.head()

sl   sw   pl   pw   flowertype
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa

In [14]:
del df['sw']

In [15]:
df.head()

sl   pl   pw   flowertype
0  4.9  1.4  0.2  Iris-setosa
1  4.7  1.3  0.2  Iris-setosa
2  4.6  1.5  0.2  Iris-setosa
3  5.0  1.4  0.2  Iris-setosa
4  5.4  1.7  0.4  Iris-setosa

In [23]:
df=iris.copy()

In [26]:
df.columns=['sl','sw','pl','pw','flowertype']

In [29]:
df.describe()

sl          sw          pl          pw
count  149.000000  149.000000  149.000000  149.000000
mean     5.848322    3.051007    3.774497    1.205369
std      0.828594    0.433499    1.759651    0.761292
min      4.300000    2.000000    1.000000    0.100000
25%      5.100000    2.800000    1.600000    0.300000
50%      5.800000    3.000000    4.400000    1.300000
75%      6.400000    3.300000    5.100000    1.800000
max      7.900000    4.400000    6.900000    2.500000

In [30]:
df['diff-pl-pw']=df['pl']-df['pw']

In [31]:
df.tail()

sl   sw   pl   pw      flowertype  diff-pl-pw
144  6.7  3.0  5.2  2.3  Iris-virginica         2.9
145  6.3  2.5  5.0  1.9  Iris-virginica         3.1
146  6.5  3.0  5.2  2.0  Iris-virginica         3.2
147  6.2  3.4  5.4  2.3  Iris-virginica         3.1
148  5.9  3.0  5.1  1.8  Iris-virginica         3.3

In [32]:
df.iloc[2:4,1:3]=0
df.head()

sl   sw   pl   pw   flowertype  diff-pl-pw
0  4.9  3.0  1.4  0.2  Iris-setosa         1.2
1  4.7  3.2  1.3  0.2  Iris-setosa         1.1
2  4.6  0.0  0.0  0.2  Iris-setosa         1.3
3  5.0  0.0  0.0  0.2  Iris-setosa         1.2
4  5.4  3.9  1.7  0.4  Iris-setosa         1.3

In [37]:
df.iloc[2:4,1:3]=np.NAN #require numpy #either we could drop these entry or NaN
df.describe()

sl          sw          pl          pw  diff-pl-pw
count  149.000000  147.000000  147.000000  149.000000  149.000000
mean     5.848322    3.046939    3.806122    1.205369    2.569128
std      0.828594    0.434048    1.750351    0.761292    1.047707
min      4.300000    2.000000    1.000000    0.100000    0.800000
25%      5.100000    2.800000    1.600000    0.300000    1.400000
50%      5.800000    3.000000    4.400000    1.300000    2.900000
75%      6.400000    3.300000    5.100000    1.800000    3.300000
max      7.900000    4.400000    6.900000    2.500000    4.700000

In [36]:
df.head()

sl   sw   pl   pw   flowertype  diff-pl-pw
0  4.9  3.0  1.4  0.2  Iris-setosa         1.2
1  4.7  3.2  1.3  0.2  Iris-setosa         1.1
2  4.6  NaN  NaN  0.2  Iris-setosa         1.3
3  5.0  NaN  NaN  0.2  Iris-setosa         1.2
4  5.4  3.9  1.7  0.4  Iris-setosa         1.3

In [40]:
df.sw.fillna(df.sw.mean(),inplace=True)
df.pl.fillna(df.pl.mean(),inplace=True) #filled with Mean
df.head()

sl   sw   pl   pw   flowertype  diff-pl-pw
0  4.9  3.0  1.4  0.2  Iris-setosa         1.2
1  4.7  3.2  1.3  0.2  Iris-setosa         1.1
2  5.4  3.9  1.7  0.4  Iris-setosa         1.3
3  4.6  3.4  1.4  0.3  Iris-setosa         1.1
4  5.0  3.4  1.5  0.2  Iris-setosa         1.3

In [38]:
df.dropna(inplace=True)# Na entries are dropped
df.head() 

sl   sw   pl   pw   flowertype  diff-pl-pw
0  4.9  3.0  1.4  0.2  Iris-setosa         1.2
1  4.7  3.2  1.3  0.2  Iris-setosa         1.1
4  5.4  3.9  1.7  0.4  Iris-setosa         1.3
5  4.6  3.4  1.4  0.3  Iris-setosa         1.1
6  5.0  3.4  1.5  0.2  Iris-setosa         1.3

In [39]:
df.reset_index(drop = True, inplace= True)
df.head()

sl   sw   pl   pw   flowertype  diff-pl-pw
0  4.9  3.0  1.4  0.2  Iris-setosa         1.2
1  4.7  3.2  1.3  0.2  Iris-setosa         1.1
2  5.4  3.9  1.7  0.4  Iris-setosa         1.3
3  4.6  3.4  1.4  0.3  Iris-setosa         1.1
4  5.0  3.4  1.5  0.2  Iris-setosa         1.3

In [41]:
# string dataset to numeric dataset
df["gender"]='female'
df.head()

sl   sw   pl   pw   flowertype  diff-pl-pw  gender
0  4.9  3.0  1.4  0.2  Iris-setosa         1.2  female
1  4.7  3.2  1.3  0.2  Iris-setosa         1.1  female
2  5.4  3.9  1.7  0.4  Iris-setosa         1.3  female
3  4.6  3.4  1.4  0.3  Iris-setosa         1.1  female
4  5.0  3.4  1.5  0.2  Iris-setosa         1.3  female

In [42]:
df.iloc[0:10,6]='Male'

In [43]:
df.head()

sl   sw   pl   pw   flowertype  diff-pl-pw gender
0  4.9  3.0  1.4  0.2  Iris-setosa         1.2   Male
1  4.7  3.2  1.3  0.2  Iris-setosa         1.1   Male
2  5.4  3.9  1.7  0.4  Iris-setosa         1.3   Male
3  4.6  3.4  1.4  0.3  Iris-setosa         1.1   Male
4  5.0  3.4  1.5  0.2  Iris-setosa         1.3   Male

In [44]:
df

sl   sw   pl   pw      flowertype  diff-pl-pw  gender
0    4.9  3.0  1.4  0.2     Iris-setosa         1.2    Male
1    4.7  3.2  1.3  0.2     Iris-setosa         1.1    Male
2    5.4  3.9  1.7  0.4     Iris-setosa         1.3    Male
3    4.6  3.4  1.4  0.3     Iris-setosa         1.1    Male
4    5.0  3.4  1.5  0.2     Iris-setosa         1.3    Male
..   ...  ...  ...  ...             ...         ...     ...
142  6.7  3.0  5.2  2.3  Iris-virginica         2.9  female
143  6.3  2.5  5.0  1.9  Iris-virginica         3.1  female
144  6.5  3.0  5.2  2.0  Iris-virginica         3.2  female
145  6.2  3.4  5.4  2.3  Iris-virginica         3.1  female
146  5.9  3.0  5.1  1.8  Iris-virginica         3.3  female

[147 rows x 7 columns]

In [46]:
def f(s):
    if s=="Male":
        return 0
    else:
        return 1
df["sex"]=df.gender.apply(f)

In [47]:
df.head()

sl   sw   pl   pw   flowertype  diff-pl-pw gender  sex
0  4.9  3.0  1.4  0.2  Iris-setosa         1.2   Male    0
1  4.7  3.2  1.3  0.2  Iris-setosa         1.1   Male    0
2  5.4  3.9  1.7  0.4  Iris-setosa         1.3   Male    0
3  4.6  3.4  1.4  0.3  Iris-setosa         1.1   Male    0
4  5.0  3.4  1.5  0.2  Iris-setosa         1.3   Male    0

In [48]:
df.tail()

sl   sw   pl   pw      flowertype  diff-pl-pw  gender  sex
142  6.7  3.0  5.2  2.3  Iris-virginica         2.9  female    1
143  6.3  2.5  5.0  1.9  Iris-virginica         3.1  female    1
144  6.5  3.0  5.2  2.0  Iris-virginica         3.2  female    1
145  6.2  3.4  5.4  2.3  Iris-virginica         3.1  female    1
146  5.9  3.0  5.1  1.8  Iris-virginica         3.3  female    1

In [49]:
del df["gender"]
df.head()

sl   sw   pl   pw   flowertype  diff-pl-pw  sex
0  4.9  3.0  1.4  0.2  Iris-setosa         1.2    0
1  4.7  3.2  1.3  0.2  Iris-setosa         1.1    0
2  5.4  3.9  1.7  0.4  Iris-setosa         1.3    0
3  4.6  3.4  1.4  0.3  Iris-setosa         1.1    0
4  5.0  3.4  1.5  0.2  Iris-setosa         1.3    0