In [1]:
from sklearn.linear_model import LinearRegression
import pandas as pd
import numpy as np

In [2]:
dataset = pd.read_csv("http://vincentarelbundock.github.io/Rdatasets/csv/mosaicData/SaratogaHouses.csv")

In [3]:
X= dataset['livingArea'].values
Y= dataset['price'].values

In [4]:
X.shape

(1728,)

In [5]:
X= X.reshape(-1,1)

In [6]:
X[:10]

array([[ 906],
       [1953],
       [1944],
       [1944],
       [ 840],
       [1152],
       [2752],
       [1662],
       [1632],
       [1416]])

In [7]:
reg =LinearRegression()
reg.fit(X,Y)

LinearRegression()

In [8]:
y_pred = reg.predict(X)

In [9]:
print(Y[:10])
print(y_pred[:10])

[132500 181115 109000 155000  86060 120000 153000 170000  90000 122900]
[115928.4169181  234367.71823171 233349.61535509 233349.61535509
 108462.32915621 143756.56221241 324752.62916731 201449.05855429
 198055.38229888 173620.91325997]


In [10]:
#pred defined fucn for reg model like coefficeint hifen 
#reg.coef_

In [12]:
reg.predict([[906]]) # for 2d to avoid error

array([115928.4169181])

In [13]:
reg.coef_

array([113.12254185])

In [15]:
from sklearn .model_selection import train_test_split

In [16]:
x_train , x_test, y_train , y_test = train_test_split(X,Y,test_size =0.20)
# 20% used for training and 20% for testing

In [17]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(1382, 1)
(346, 1)
(1382,)
(346,)


In [18]:
reg_2 = LinearRegression()

In [19]:
reg_2.fit(x_train, y_train)

LinearRegression()

In [22]:
y_pred = reg_2.predict(x_test)

In [27]:
from sklearn.metrics import mean_squared_error

In [24]:
mse = mean_squared_error(y_test, y_pred)

In [25]:
rmse= np.sqrt(mse)

In [26]:
mse,rmse
#we can further reduce the error by pre processing the data

(5192675997.207553, 72060.22479292964)